// Generated by CoffeeScript 1.4.0

/*
Copyright (C) 2012 Ohso Ltd

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

  http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing,
software distributed under the License is distributed on an
"AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
KIND, either express or implied.  See the License for the
specific language governing permissions and limitations
under the License.
*/


(function() {
  'use strict';

  var buttons, data, notifications, popup, request, self, tabs, widget, widgets;

  widgets = require('widget');

  buttons = require('toolbarbutton');

  tabs = require('tabs');

  self = require('self');

  data = require('self').data;

  request = require('request').Request;

  notifications = require('sdk/notifications');

  popup = require('panel').Panel({
    width: 464,
    height: 512,
    contentURL: data.url('popup.html'),
    contentScriptFile: [data.url('scripts/jquery.min.js'), data.url('scripts/angular.min.js'), data.url('scripts/angular-resource.min.js'), data.url('scripts/popup.js')]
  });

  widget = widgets.Widget({
    id: 'omg-bubble',
    label: 'OMG! Ubuntu!',
    contentURL: data.url('images/icon19.png'),
    panel: popup
  });

  popup.port.on('getArticles', function(feedUrl) {
    return request({
      url: feedUrl,
      onComplete: function(response) {
        return popup.port.emit('receivedArticles', response.text);
      }
    }).get();
  });

  popup.port.on('updateBadge', function(unread) {
    if (unread === '0') {
      return widget.contentURL = data.url('images/icon_unread19.png');
    } else {
      return widget.contentURL = data.url('images/icon19.png');
    }
  });

  popup.port.on('notification', function(notify) {
    if (notify.count === 1) {
      return notifications.notify({
        title: "New article on OMG! Ubuntu!",
        text: notify.title,
        iconURL: data.url('images/icon48.png')
      });
    } else if (notify.count > 1) {
      return notifications.notify({
        title: "New articles on OMG! Ubuntu!",
        text: "" + notify.count + " new articles",
        iconURL: data.url('images/icon48.png')
      });
    }
  });

}).call(this);
